elements:
  storage_price:
    label: 'Storage Price'
    xpath: '/html/body/div/div/main/div[3]/div/div/div[1]/div/div[1]/div/div[10]/section/div[2]/div/div[1]/div/div[1]/div[2]/div/span[1]'
    command: minstorageprice
    unit: SCP
  collateral_price:
    label: 'Collateral Price'
    xpath: '/html/body/div/div/main/div[3]/div/div/div[1]/div/div[1]/div/div[10]/section/div[2]/div/div[2]/div/div[1]/div[2]/div/span[1]'
    command: collateral
    unit: SCP
  max_collateral:
    label: 'Max Collateral'
    xpath: '/html/body/div/div/main/div[3]/div/div/div[1]/div/div[1]/div/div[10]/section/div[2]/div/div[3]/div/div[1]/div[2]/div/span[1]'
    command: maxcollateral
    unit: SCP
  download_bandwith_price:
    label: 'Download Bandwith Price'
    xpath: '/html/body/div/div/main/div[3]/div/div/div[1]/div/div[1]/div/div[10]/section/div[2]/div/div[4]/div/div[1]/div[2]/div/span[1]'
    command: mindownloadbandwidthprice
    unit: SCP
  upload_bandwith_price:
    label: 'Upload Bandwith Price'
    xpath: '/html/body/div/div/main/div[3]/div/div/div[1]/div/div[1]/div/div[10]/section/div[2]/div/div[5]/div/div[1]/div[2]/div/span[1]'
    command: minuploadbandwidthprice
    unit: SCP
  contract_duration:
    label: 'Contract Duration'
    xpath: '/html/body/div/div/main/div[3]/div/div/div[1]/div/div[1]/div/div[10]/section/div[2]/div/div[6]/div/div[1]/div[2]/div/span[1]'
  contract_creation_fee:
    label: 'Contract Creation Fee'
    xpath: '/html/body/div/div/main/div[3]/div/div/div[1]/div/div[1]/div/div[10]/section/div[2]/div/div[7]/div/div[1]/div[2]/div/span[1]'
